# Generated by Django 4.2.2 on 2023-06-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomsize",
            old_name="r_size",
            new_name="room_size",
        ),
        migrations.RenameField(
            model_name="roomtype",
            old_name="r_type",
            new_name="room_type",
        ),
    ]
