# Generated by Django 4.2.2 on 2023-06-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0003_rename_daily_rate_roomrate_room_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_rate",
        ),
    ]
